/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/Users/andeladeveloper/.choosenim/toolchains/nim-0.18.0/lib -o '/Users/andeladeveloper/Desktop/Test Codes/nimcache/test.o' '/Users/andeladeveloper/Desktop/Test Codes/nimcache/test.c' */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
typedef NI tyArray_Bd4h7Ocx9bGTvrKzPIWNlHw[3];
typedef NimStringDesc* tyArray_sMpvt1sOxOJ3LFGulnbeMQ[4];
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__kKwBoyXI6gKwKAFIW1DTjQ)(tyArray_Bd4h7Ocx9bGTvrKzPIWNlHw x);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NIM_BOOL, contains_P6sCVNQ9cdTFh3rtVXMEtxgtest)(NI* a, NI aLen_0, NI item);
static N_INLINE(NI, find_b2asjP2y9cPDPwOLa1pD5PAtest)(NI* a, NI aLen_0, NI item);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NimStringDesc*, nimBoolToStr)(NIM_BOOL x);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, collectionToString_TtrPdzsaVfFUJf5k1e89aaQ)(tyArray_Bd4h7Ocx9bGTvrKzPIWNlHw x, NimStringDesc* prefix, NimStringDesc* separator, NimStringDesc* suffix);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted_nyaZAljVI03SH2d9cnD0WMw)(NimStringDesc** s, NI x);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, testDatInit000)(void);
tyArray_Bd4h7Ocx9bGTvrKzPIWNlHw x_9bf4p1FLrvkXIchOKUUtCcw;
NI i_vyCYEvJNp9c9b1bD8JVdQqrQ;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
STRING_LITERAL(TM_ipcYmBC9bj9a1BW35ABoB1Kw_3, "Hello world!", 12);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_ipcYmBC9bj9a1BW35ABoB1Kw_2 = {((NimStringDesc*) &TM_ipcYmBC9bj9a1BW35ABoB1Kw_3)}
;
NIM_CONST tyArray_Bd4h7Ocx9bGTvrKzPIWNlHw TM_ipcYmBC9bj9a1BW35ABoB1Kw_4 = {((NI) 1),
((NI) 2),
((NI) 3)}
;
STRING_LITERAL(TM_ipcYmBC9bj9a1BW35ABoB1Kw_5, "Hello ", 6);
STRING_LITERAL(TM_ipcYmBC9bj9a1BW35ABoB1Kw_6, " ", 1);

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(NI, find_b2asjP2y9cPDPwOLa1pD5PAtest)(NI* a, NI aLen_0, NI item) {
	NI result;
	nimfr_("find", "system.nim");
{	result = (NI)0;
	{
		NI i;
		NI i_2;
		i = (NI)0;
		nimln_(2185, "system.nim");
		i_2 = ((NI) 0);
		{
			nimln_(2186, "system.nim");
			while (1) {
				NI TM_ipcYmBC9bj9a1BW35ABoB1Kw_8;
				NI TM_ipcYmBC9bj9a1BW35ABoB1Kw_9;
				if (!(i_2 < aLen_0)) goto LA3;
				nimln_(2187, "system.nim");
				if ((NU)(i_2) >= (NU)(aLen_0)) raiseIndexError();
				i = a[i_2];
				nimln_(2419, "system.nim");
				{
					if (!(i == item)) goto LA6_;
					goto BeforeRet_;
				}
				LA6_: ;
				nimln_(2420, "system.nim");
				TM_ipcYmBC9bj9a1BW35ABoB1Kw_8 = addInt(result, ((NI) 1));
				result = (NI)(TM_ipcYmBC9bj9a1BW35ABoB1Kw_8);
				nimln_(2188, "system.nim");
				TM_ipcYmBC9bj9a1BW35ABoB1Kw_9 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_ipcYmBC9bj9a1BW35ABoB1Kw_9);
			} LA3: ;
		}
	}
	nimln_(2421, "system.nim");
	result = ((NI) -1);
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, contains_P6sCVNQ9cdTFh3rtVXMEtxgtest)(NI* a, NI aLen_0, NI item) {
	NIM_BOOL result;
	NI T1_;
	nimfr_("contains", "system.nim");
{	result = (NIM_BOOL)0;
	nimln_(2426, "system.nim");
	T1_ = (NI)0;
	T1_ = find_b2asjP2y9cPDPwOLa1pD5PAtest(a, aLen_0, item);
	result = (((NI) 0) <= T1_);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	testDatInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	tyArray_nHXaesL0DJZHyVS07ARPRA T5_;
	NIM_BOOL T6_;
	nimfr_("test", "test.nim");
	nimln_(1, "test.nim");
	echoBinSafe(TM_ipcYmBC9bj9a1BW35ABoB1Kw_2, 1);
	nimln_(2, "test.nim");
	memcpy((void*)x_9bf4p1FLrvkXIchOKUUtCcw, (NIM_CONST void*)TM_ipcYmBC9bj9a1BW35ABoB1Kw_4, sizeof(tyArray_Bd4h7Ocx9bGTvrKzPIWNlHw));
	{
		NI res;
		nimln_(2045, "system.nim");
		res = ((NI) 3);
		{
			nimln_(2046, "system.nim");
			while (1) {
				tyArray_sMpvt1sOxOJ3LFGulnbeMQ T4_;
				NI TM_ipcYmBC9bj9a1BW35ABoB1Kw_7;
				if (!(res <= ((NI) 11))) goto LA3;
				nimln_(2047, "system.nim");
				i_vyCYEvJNp9c9b1bD8JVdQqrQ = res;
				nimln_(5, "test.nim");
				memset((void*)T4_, 0, sizeof(T4_));
				T4_[0] = copyString(((NimStringDesc*) &TM_ipcYmBC9bj9a1BW35ABoB1Kw_5));
				T4_[1] = nimIntToStr(i_vyCYEvJNp9c9b1bD8JVdQqrQ);
				T4_[2] = copyString(((NimStringDesc*) &TM_ipcYmBC9bj9a1BW35ABoB1Kw_6));
				T4_[3] = dollar__kKwBoyXI6gKwKAFIW1DTjQ(x_9bf4p1FLrvkXIchOKUUtCcw);
				echoBinSafe(T4_, 4);
				nimln_(2048, "system.nim");
				TM_ipcYmBC9bj9a1BW35ABoB1Kw_7 = addInt(res, ((NI) 1));
				res = (NI)(TM_ipcYmBC9bj9a1BW35ABoB1Kw_7);
			} LA3: ;
		}
	}
	nimln_(7, "test.nim");
	memset((void*)T5_, 0, sizeof(T5_));
	T6_ = (NIM_BOOL)0;
	T6_ = contains_P6sCVNQ9cdTFh3rtVXMEtxgtest(x_9bf4p1FLrvkXIchOKUUtCcw, 3, ((NI) 1));
	T5_[0] = nimBoolToStr(T6_);
	echoBinSafe(T5_, 1);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, testDatInit000)(void) {
}

